### PR TITLE
enable more linters

### PR DESCRIPTION
**Pull request by lburgazzoli**
- **fix(lint): enable cyclop**
- **fix(lint): enable gocognit**
- **fix(lint): enable funlen**
- **fix(lint): enable gochecknoinits**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@salaboy mind having a look ?

**Review by salaboy — APPROVED** [review]
@lburgazzoli thanks for this! LGTM!

**Review by salaboy — DISMISSED** [review]
LGMT

**Review by salaboy — APPROVED** [review]
LGTM

**Pull request merged**
